### PR TITLE
eslint setup configuration

### PR DESCRIPTION
**Pull request by Millionhat**
Added setup files and fixed errors for eslint

### CODE REVIEW

**Review by manuelq12 — COMMENTED** [review]
I think you have mixed stuff here on this PR.

Its your first test and you started adding the Typescript config, right?

Did you do step 4 and 5? Or If so show me the tsconfig.json and the webpack.config.js

If not, let me know

**Comment by Millionhat** [comment]
> I think you have mixed stuff here on this PR.
> 
> Its your first test and you started adding the Typescript config, right?
> 
> Did you do step 4 and 5? Or If so show me the tsconfig.json and the webpack.config.js
> 
> If not, let me know

it has step 4, 5 and 6 in one commit (I know it shouldn´t be done)

**Comment by manuelq12** [comment]
@Millionhat I only see 2 files changed, can you show me tsconfig.json and the webpack.config.js please?
And package json, there isn't any changes?

It seems that the only uploaded changes were from step 4 and the beginning of step 5

**Comment by Millionhat** [comment]
> @Millionhat I only see 2 files changed, can you show me tsconfig.json and the webpack.config.js please?
> And package json, there isn't any changes?
> 
> It seems that the only uploaded changes were from step 4 and the beginning of step 5

image
image

**Comment by Millionhat** [comment]
presione el boton que no era xd

**Review by manuelq12 — COMMENTED** [review]
@Millionhat Can you add a screenshot of the test on green please?

**Comment by Millionhat** [comment]
> @Millionhat Can you add a screenshot of the test on green please?

image

**Review by manuelq12 — APPROVED** [review]

**Pull request merged**
